"""initial schema

Revision ID: a04bd5bb27f8
Revises: 
Create Date: 2026-09-17 01:31:23.915689
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a04bd5bb27f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('notification',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_user_id', 'notification', ['user_id'], unique=False)
    op.create_index('ix_notification_user_read', 'notification', ['user_id', 'read'], unique=False)
    op.create_table('session',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_refresh_token'), 'session', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_session_token'), 'session', ['token'], unique=True)
    op.create_table('storageusage',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('limit_bytes', sa.BigInteger(), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wedding',
    sa.Column('wedding_name', sa.String(length=255), nullable=False),
    sa.Column('bride_name', sa.String(length=255), nullable=False),
    sa.Column('groom_name', sa.String(length=255), nullable=False),
    sa.Column('wedding_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('wedding_code', sa.String(length=50), nullable=False),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('photographer_id', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('total_photos', sa.Integer(), nullable=False),
    sa.Column('total_albums', sa.Integer(), nullable=False),
    sa.Column('total_folders', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photographer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wedding_photographer_id', 'wedding', ['photographer_id'], unique=False)
    op.create_index('ix_wedding_status', 'wedding', ['status'], unique=False)
    op.create_index('ix_wedding_visibility', 'wedding', ['visibility'], unique=False)
    op.create_index(op.f('ix_wedding_wedding_code'), 'wedding', ['wedding_code'], unique=True)
    op.create_table('activity',
    sa.Column('wedding_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_created_at', 'activity', ['created_at'], unique=False)
    op.create_index('ix_activity_type', 'activity', ['type'], unique=False)
    op.create_index('ix_activity_user_id', 'activity', ['user_id'], unique=False)
    op.create_index('ix_activity_wedding_id', 'activity', ['wedding_id'], unique=False)
    op.create_table('album',
    sa.Column('wedding_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_album_wedding_id', 'album', ['wedding_id'], unique=False)
    op.create_index('ix_album_wedding_sort', 'album', ['wedding_id', 'sort_order'], unique=False)
    op.create_table('download',
    sa.Column('wedding_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_download_user_id', 'download', ['user_id'], unique=False)
    op.create_index('ix_download_wedding_id', 'download', ['wedding_id'], unique=False)
    op.create_table('folder',
    sa.Column('wedding_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_folder_wedding_id', 'folder', ['wedding_id'], unique=False)
    op.create_index('ix_folder_wedding_sort', 'folder', ['wedding_id', 'sort_order'], unique=False)
    op.create_table('participant',
    sa.Column('wedding_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_participant_status', 'participant', ['status'], unique=False)
    op.create_index('ix_participant_user_id', 'participant', ['user_id'], unique=False)
    op.create_index('ix_participant_wedding_id', 'participant', ['wedding_id'], unique=False)
    op.create_table('permission',
    sa.Column('wedding_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wedding_id', 'role', 'permission', name='uq_wedding_role_permission')
    )
    op.create_table('sharelink',
    sa.Column('wedding_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('download_enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharelink_code'), 'sharelink', ['code'], unique=True)
    op.create_table('photo',
    sa.Column('wedding_id', sa.String(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=True),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('medium_path', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('blur_hash', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('camera', sa.String(length=255), nullable=True),
    sa.Column('lens', sa.String(length=255), nullable=True),
    sa.Column('aperture', sa.String(length=50), nullable=True),
    sa.Column('shutter_speed', sa.String(length=50), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('focal_length', sa.String(length=50), nullable=True),
    sa.Column('date_taken', sa.DateTime(timezone=True), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('is_highlight', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photo_album_id', 'photo', ['album_id'], unique=False)
    op.create_index('ix_photo_favorite', 'photo', ['favorite'], unique=False)
    op.create_index('ix_photo_folder_id', 'photo', ['folder_id'], unique=False)
    op.create_index('ix_photo_is_deleted', 'photo', ['is_deleted'], unique=False)
    op.create_index('ix_photo_wedding_album_folder', 'photo', ['wedding_id', 'album_id', 'folder_id'], unique=False)
    op.create_index('ix_photo_wedding_id', 'photo', ['wedding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_wedding_id', table_name='photo')
    op.drop_index('ix_photo_wedding_album_folder', table_name='photo')
    op.drop_index('ix_photo_is_deleted', table_name='photo')
    op.drop_index('ix_photo_folder_id', table_name='photo')
    op.drop_index('ix_photo_favorite', table_name='photo')
    op.drop_index('ix_photo_album_id', table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_sharelink_code'), table_name='sharelink')
    op.drop_table('sharelink')
    op.drop_table('permission')
    op.drop_index('ix_participant_wedding_id', table_name='participant')
    op.drop_index('ix_participant_user_id', table_name='participant')
    op.drop_index('ix_participant_status', table_name='participant')
    op.drop_table('participant')
    op.drop_index('ix_folder_wedding_sort', table_name='folder')
    op.drop_index('ix_folder_wedding_id', table_name='folder')
    op.drop_table('folder')
    op.drop_index('ix_download_wedding_id', table_name='download')
    op.drop_index('ix_download_user_id', table_name='download')
    op.drop_table('download')
    op.drop_index('ix_album_wedding_sort', table_name='album')
    op.drop_index('ix_album_wedding_id', table_name='album')
    op.drop_table('album')
    op.drop_index('ix_activity_wedding_id', table_name='activity')
    op.drop_index('ix_activity_user_id', table_name='activity')
    op.drop_index('ix_activity_type', table_name='activity')
    op.drop_index('ix_activity_created_at', table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_wedding_wedding_code'), table_name='wedding')
    op.drop_index('ix_wedding_visibility', table_name='wedding')
    op.drop_index('ix_wedding_status', table_name='wedding')
    op.drop_index('ix_wedding_photographer_id', table_name='wedding')
    op.drop_table('wedding')
    op.drop_table('storageusage')
    op.drop_index(op.f('ix_session_token'), table_name='session')
    op.drop_index(op.f('ix_session_refresh_token'), table_name='session')
    op.drop_table('session')
    op.drop_index('ix_notification_user_read', table_name='notification')
    op.drop_index('ix_notification_user_id', table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
