"""reactions faces downloads pin

Revision ID: c1f59877d3ec
Revises: a04bd5bb27f8
Create Date: 2026-09-17 02:10:16.859881
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c1f59877d3ec'
down_revision: Union[str, None] = 'a04bd5bb27f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faceprofile',
    sa.Column('wedding_id', sa.String(), nullable=False),
    sa.Column('photo_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('face_box', sa.JSON(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_profile_photo_id', 'faceprofile', ['photo_id'], unique=False)
    op.create_index('ix_face_profile_wedding_id', 'faceprofile', ['wedding_id'], unique=False)
    op.create_table('photoreaction',
    sa.Column('photo_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'user_id', name='uq_photo_reaction_photo_user')
    )
    op.create_index('ix_photo_reaction_photo_id', 'photoreaction', ['photo_id'], unique=False)
    op.create_index('ix_photo_reaction_user_id', 'photoreaction', ['user_id'], unique=False)
    op.add_column('album', sa.Column('download_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('download', sa.Column('photo_ids', sa.JSON(), nullable=True))
    op.add_column('photo', sa.Column('download_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('sharelink', sa.Column('pin_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sharelink', 'pin_code')
    op.drop_column('photo', 'download_enabled')
    op.drop_column('download', 'photo_ids')
    op.drop_column('album', 'download_enabled')
    op.drop_index('ix_photo_reaction_user_id', table_name='photoreaction')
    op.drop_index('ix_photo_reaction_photo_id', table_name='photoreaction')
    op.drop_table('photoreaction')
    op.drop_index('ix_face_profile_wedding_id', table_name='faceprofile')
    op.drop_index('ix_face_profile_photo_id', table_name='faceprofile')
    op.drop_table('faceprofile')
    # ### end Alembic commands ###
